### ISSUE TITLE
Cannot install for QGIS 3.16 / What are the requirements ?

### ISSUE THREAD

**Issue by MaelREBOUX** [3dcitydb/3dcitydb-qgis-explorer#7]
Hello.

Your plugin seems to be great. But I cannot install it.

The steps :

- download the current release from here
- load the zip in the plugin manger

```
ModuleNotFoundError: No module named '3dcitydb-qgis-explorer-0' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS/3.16/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS/3.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named '3dcitydb-qgis-explorer-0'


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.16.8-Hannover Hannover, 8c50902ea4 
```

**Comment by MaelREBOUX** [comment]
No more succes with QGIS 3.22 : same error.
